apiVersion: v1
kind: Template
labels:
  template: telanlyt-api
metadata:
  name: telanlyt-api
  annotations:
    description: A template that contains the deploymentconfig for telemetry analytics API server deployment.
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        service: telanlyt-api
      name: telanlyt-api
    spec:
      replicas: "${{REPLICAS}}"
      selector:
        service: telanlyt-api
      template:
        metadata:
          labels:
            service: telanlyt-api
        spec:
          containers:
            - command:
                - ./entrypoint.sh
              envFrom:
                - configMapRef:
                    name: telanlyt-config
                - secretRef:
                    name: telanlyt-secrets
              env:
                - name: API_SERVER_PORT
                  value: ${API_SERVER_PORT}
                - name: API_SERVER_TIMEOUT
                  value: ${API_SERVER_TIMEOUT}
                - name: NUMBER_WORKER_PROCESS
                  value: ${NUMBER_WORKER_PROCESS}
                - name: WORKER_TYPE
                  value: ${WORKER_TYPE}
                - name: WORKER_CONNECTION_POOL_LIMIT
                  value: ${WORKER_CONNECTION_POOL_LIMIT}

              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              name: telanlyt-api
              ports:
                - containerPort: ${{API_SERVER_PORT}}
              livenessProbe:
                httpGet:
                  path: /api/v1/
                  port: ${{API_SERVER_PORT}}
                initialDelaySeconds: 60
                periodSeconds: 60
                timeoutSeconds: 30
                failureThreshold: 3
                successThreshold: 1
              readinessProbe:
                httpGet:
                  path: /api/v1/readiness
                  port: ${{API_SERVER_PORT}}
                failureThreshold: 3
                successThreshold: 1
                initialDelaySeconds: 60
                periodSeconds: 60 # check whether DB is live once every minute.
                timeoutSeconds: 30
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        service: telanlyt-api
      name: telanlyt-api
    spec:
      ports:
        - port: ${{API_SERVER_PORT}}
          name: "${API_SERVER_PORT}"
          targetPort: ${{API_SERVER_PORT}}
          protocol: TCP
      selector:
        service: telanlyt-api
  - apiVersion: v1
    kind: Route
    metadata:
      name: telanlyt-api
    spec:
      to:
        kind: Service
        name: telanlyt-api

parameters:
  - description: CPU request
    displayName: CPU request
    required: true
    name: CPU_REQUEST
    value: "128m"

  - description: CPU limit
    displayName: CPU limit
    required: true
    name: CPU_LIMIT
    value: "500m"

  - description: Memory request
    displayName: Memory request
    required: true
    name: MEMORY_REQUEST
    value: "256Mi"

  - description: Memory limit
    displayName: Memory limit
    required: true
    name: MEMORY_LIMIT
    value: "1Gi"

  - description: Docker registry where the image is
    displayName: Docker registry
    required: true
    name: DOCKER_REGISTRY
    value: "quay.io"

  - description: Docker image to use
    displayName: Docker image
    required: true
    name: DOCKER_IMAGE
    value: "rootavish/telanlyt-api"

  - description: Image tag
    displayName: Image tag
    required: true
    name: IMAGE_TAG
    value: "latest"

  - description: Number of deployment replicas
    displayName: Number of deployment replicas
    required: true
    name: REPLICAS
    value: "3"

  - description: Port Number
    displayName: Port Number
    required: true
    name: API_SERVER_PORT
    value: "6006"

  - description: The application gateway timeout for the apiserver for each request
    displayName: API Server Timeout
    name: API_SERVER_TIMEOUT
    value: "90"

  - description: Number of gunicorn worker processes
    displayName: Number of worker processes
    required: true
    name: NUMBER_WORKER_PROCESS
    value: "4"

  - description: Type of gunicorn worker (sync/async)
    displayName: Worker type
    required: true
    name: WORKER_TYPE
    value: "gevent"

  - description: Connection pool size for each gevent worker
    displayName: Worker Pool Size
    required: true
    name: WORKER_CONNECTION_POOL_LIMIT
    value: "1024"
